export const GET_CONTACTS_REQUESTED = 'GET_CONTACTS_REQUESTED';
export const GET_CONTACTS_SUCCESS = 'GET_CONTACTS_SUCCESS';
export const GET_CONTACTS_FAILED = 'GET_CONTACTS_FAILED';
export const GET_CONTACTSDETAIL_REQUESTED = 'GET_CONTACTSDETAIL_REQUESTED'
export const GET_CONTACTSDETAIL_SUCCESS = 'GET_CONTACTSDETAIL_SUCCESS'
export const GET_CONTACTSDETAIL_FAILED = 'GET_CONTACTSDETAIL_FAILED'